--初始化脚本,第一次运行打开
-- INSERT INTO user VALUES ('0001', '耿鑫1', 1, '我要打十个', 'aaa.jpg');
-- INSERT INTO user VALUES ('0002', '耿鑫2', 1, '我要打十个！', 'aaa.jpg');
-- INSERT INTO user VALUES ('0003', '耿鑫3', 0, '我要打十个！', 'aaa.jpg');
